title: Byrch's Blog
author: Byrch Baker
email: byrchbaker@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Meet Byrch Baker, a passionate and dedicated Cyber Security Enthusiast and Programmer. Byrch is an aspiring cybersecurity student currently in high school, graduating in May 2026.

  With a strong foundation in technology and an impressive array of skills, Byrch has actively engaged in various clubs and activities. As the Captain of CyberPatriot and an A1C in JROTC, Byrch has demonstrated exceptional leadership and problem-solving abilities. Additionally, Byrch's experience as the President of the Class Officer and a Member of Key Club highlights their commitment to community involvement.

  Byrch's hands-on experience includes freelance tech support, where they have offered comprehensive troubleshooting and communicated complex technical concepts effectively to assist clients. Having provided over 50+ hours of service to the community, Byrch's dedication to helping others is evident.

  Byrch's technical expertise spans Windows Servers, Active Directory, DNS, IIS, Python, PowerShell, and more, showcasing their versatility in the field of cybersecurity. They possess a remarkable ability to learn quickly, are self-taught, resourceful, and always eager to improve their skills.

  With multiple accolades and awards, including CyberPatriot State Award - 1st Place, CyberPatriot AFA Award - Top 10, and recognition from the University of North Texas, Byrch has already made significant achievements in the cybersecurity realm.

  Join Byrch Baker on their journey to becoming a cybersecurity professional, where their passion, skills, and dedication promise an exciting and rewarding future in the ever-evolving world of cybersecurity.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Byrch Baker
  tagline: Student. Cyber Security Enthusiast. Programmer.
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/portfolio.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    github:  byrchbaker
    linkedIn: in/byrchbaker
  analytics_id: "G-0ZSCKXMDGP"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
remote_theme: samarsault/plainwhite-jekyll

plugins:
  - jekyll-seo-tag
  - jekyll-feed
